config/routes.rb
Rails.application.routes.draw do
  
  get 'auth/:provider/callback', to: 'sessions#callback'
  get 'users/logout', to: 'sessions#destroy'
  get 'users/registration', to: 'sessions#registration', as: 'user_registration'
  patch 'users/registration', to: 'sessions#confirmation'
  
  namespace :activity_watcher, path: 'activity-watcher', as: "" do
    get '/', to: 'homes#index', as: 'activity_watcher'
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
end

app/views/layouts/common/_sidebar.html.erb
<div class="sidebar">
  <div class="sidebar__wrap">
<!-- sidebar menu -->
    <div class="sidebar__menu-wrap">
      <div>
        <ul>
          <li class="sidebar__items">
            <%= link_to activity_watcher_path do %>
              <div class="sidebar__item"><i class="fa fa-home" aria-hidden="true"></i><span class="sidebar__action">ホーム</span></div>
            <% end %>
          </li>
          <li class="sidebar__items">
            <%= link_to "/" do %>
              <div class="sidebar__item"><i class="fa fa-files-o" aria-hidden="true"></i><span class="sidebar__action">コース登録</span></div>
            <% end %>
          </li>
          <li class="sidebar__items">
            <%= link_to "/" do %>
              <div class="sidebar__item"><i class="fa fa-files-o" aria-hidden="true"></i><span class="sidebar__action">コース登録</span></div>
            <% end %>
          </li>
          <li class="sidebar__items">
            <%= link_to "/" do %>
              <div class="sidebar__item"><i class="fa fa-files-o" aria-hidden="true"></i><span class="sidebar__action">コース登録</span></div>
            <% end %>
          </li>
          <li class="sidebar__items">
            <%= link_to "/" do %>
              <div class="sidebar__item"><i class="fa fa-files-o" aria-hidden="true"></i><span class="sidebar__action">コース登録</span></div>
            <% end %>
          </li>
          <li class="sidebar__items">
            <%= link_to "/" do %>
              <div class="sidebar__item"><i class="fa fa-files-o" aria-hidden="true"></i><span class="sidebar__action">コース登録</span></div>
            <% end %>
          </li>
          <li class="sidebar__items">
            <%= link_to users_logout_path do %>
              <div class="sidebar__item"><i class="fa fa-files-o" aria-hidden="true"></i><span class="sidebar__action">ログアウト</span></div>
            <% end %>
          </li>          
        </ul>
      </div>
    </div>
<!-- /sidebar__menu -->
  </div>
</div>
<!-- /sidebar -->